### ISSUE TITLE
Want help putting onto CPAN?

### ISSUE THREAD

**Issue by mohawk2** [zenogantner/PDL-ML#1]
I'd love to see this code on CPAN. All it would need is simple tests and a bit of packaging. If you're interested and can tell me where to get suitable test inputs that produce correct outputs, I'll be pleased to PR them, and then either upload to CPAN or assist you in doing so.

If you'd like an even-easier solution, you could add me as a "collaborator" on this repo, then I can do the necessary. I can upload it to CPAN under my ID, then add you as co-maintainer (or primary owner) if you have a PAUSE ID.

Let me know!

**Comment by zenogantner** [comment]
Hello, sorry for the late reply.

As the README says, this is experimental code. I do not think it makes sense to offer it as a CPAN module, as it does not offer functionality that would provide value to users (programmers): People who understand that stuff can either implement it themselves, or know which packages to use instead. And Perl programmers who do not know the concepts will have trouble using the code correctly -- unless a significant amount of work is put into the code.
I think having it in CPAN would give people the wrong impression, and lead them on to invest time in something that is not really ready to be used by another program.
